name: Main CI

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Sources
      uses: actions/checkout@v2
      
    - name: Run a one-line script
      run: echo Hello, world!

    - name: Setting up Java
      uses: actions/setup-java@v1
      with:
        java-version: '12.x'

    - name: Setting up Flutter
      uses: subosito/flutter-action@v1
      with:
        channel: 'dev'

    - name: Get dependencies
      run: flutter pub get
      
    - name: Build release APK
      run: flutter build apk --release
      
    - name: Upload artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        name: Release Artifacts
        path: build/app/outputs/flutter-apk

    - name: Deploy APK to myrunes DL server
      run: |
        gpg --batch --yes --passphrase="${{ secrets.SSH_KEY_PASSPHRASE }}" -o ssh_key.pem -d key.pem.gpg
        chmod 0700 ssh_key.pem
        mkdir ~/.ssh
        ssh-keyscan -t rsa myrunes.com >> ~/.ssh/known_hosts
        scp -i ssh_key.pem build/app/outputs/flutter-apk/app-release.apk myrunespush@myrunes.com:/var/www/html/files/myrunes/download/beta-app.apk